### ISSUE TITLE
Crashes when creating a concept when running locally

### ISSUE THREAD

**Issue by jruehlin** [watson-developer-cloud/concept-insights-nodejs#46]
Download the code locally, get credentials and service URL from the command line, and update the credentials variable in app.js per instructions. Note that my URL is url: `https://gateway-s.watsonplatform.net/concept-insights/api` (running on stage1.ng.bluemix.net).

npm install, then npm start. Launch browser at localhost:3000.

In the Concepts tab, enter any text and select a concept that comes up. The Output section of the page shows static text (no actual output from TED talks) and the app crashes with the following:

```listening at: 3000
/Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/app.js:114
  var documentText = doc.parts[tag.parts_index].data;
                                                 ^

TypeError: Cannot read property '0' of undefined
    at crop (/Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/app.js:114:31)
    at Array.forEach (native)
    at /Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/app.js:99:30
    at Request._callback (/Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/node_modules/watson-developer-cloud/lib/requestwrapper.js:68:5)
    at Request.self.callback (/Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/node_modules/watson-developer-cloud/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/jruehlin/Documents/Dev/concept-insights-nodejs-master/node_modules/watson-developer-cloud/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! conceptInsightsNodejsStarterApp@1.1.8 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the conceptInsightsNodejsStarterApp@1.1.8 start script 'node app.js'.
```

**Comment by jruehlin** [comment]
Note that in the log output above, the pointer should be just after doc.parts, at the "[". It appears that the doc parameter is passed as null.

**Comment by kognate** [comment]
Do you get a crash when you deploy to bluemix?

**Comment by jruehlin** [comment]
No, just when I'm running it locally. Maybe there's an extra VCAP_SERVICES param?

**Comment by germanattanasio** [comment]
I can run the app locally without problems. Make sure you replace `username`, `password` and `url` since you are running in stage1.

And make sure you don't mention stage1 since it's internal to IBMers
